CREATE TABLE [wvg].[Steun Ontvanger] (
    [ID Steun Ontvanger] INT            IDENTITY (1, 1) NOT NULL,
    [Code]               VARCHAR (20)   NULL,
    [Type]               VARCHAR (50)   NOT NULL,
    [Details]            VARCHAR (MAX)  NULL,
    [URL Info]           VARCHAR (1000) NULL,
    [Paspoort Nr]        VARCHAR (30)   NULL,
    [Belgisch ID]        VARCHAR (20)   NULL,
    [Voornaam]           VARCHAR (100)  NULL,
    [Familienaam]        VARCHAR (100)  NULL,
    [Geboorteplaats]     VARCHAR (100)  NULL,
    [Geboortedatum]      DATE           NULL,
    [Religie]            VARCHAR (100)  NULL,
    [Bankrekening]       VARCHAR (20)   NULL,
    [Adres]              VARCHAR (255)  NULL,
    [Straat]             VARCHAR (100)  NULL,
    [Postcode]           VARCHAR (50)   NULL,
    [Woonplaats]         VARCHAR (100)  NULL,
    [Telefoon]           VARCHAR (50)   NULL,
    [Email]              VARCHAR (100)  NULL,
    [Functie]            VARCHAR (50)   NULL,
    [Geslacht]           CHAR (1)       NULL,
    [Spreektaal]         VARCHAR (100)  NULL,
    [ID Gezin]           INT            NULL,
    [Rol in Gezin]       VARCHAR (50)   NULL,
    [Laatste Wijziging]  DATETIME       NULL,
    [Rowversion]         ROWVERSION     NULL,
    CONSTRAINT [PK_Steun Ontvanger] PRIMARY KEY CLUSTERED ([ID Steun Ontvanger] ASC),
    CONSTRAINT [FK_Steun Ontvanger_Gezin] FOREIGN KEY ([ID Gezin]) REFERENCES [wvg].[Gezin] ([ID Gezin])
);

